services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wiki_streamlit
    env_file:
      - .env
    command: streamlit run src/streamlit_app.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wiki_pipeline
    env_file:
      - .env
    command: python src/pipeline.py
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
